-- Generado por web/scripts/generar-productos.mjs · no editar a mano
insert into public.productos (slug, titulo, categoria, subcategoria, unidad, precio, color, stock, destacado, descripcion)
values
  ('hilo-de-coser-poliester-100-m-negro', 'Hilo de coser poliéster 100 m · Negro', 'Hilos', 'Poliéster', 'u', 1200, '#1E1B19', 48, true, 'Hilo de coser poliéster 100 m · Negro. Hilos · Poliéster. Precio por unidad.'),
  ('hilo-de-coser-poliester-100-m-blanco', 'Hilo de coser poliéster 100 m · Blanco', 'Hilos', 'Poliéster', 'u', 1200, '#F7F4EE', 52, false, 'Hilo de coser poliéster 100 m · Blanco. Hilos · Poliéster. Precio por unidad.'),
  ('hilo-de-coser-poliester-100-m-rosa-texma', 'Hilo de coser poliéster 100 m · Rosa TEXMA', 'Hilos', 'Poliéster', 'u', 1250, '#EC1968', 30, true, 'Hilo de coser poliéster 100 m · Rosa TEXMA. Hilos · Poliéster. Precio por unidad.'),
  ('hilo-de-coser-poliester-100-m-azul-marino', 'Hilo de coser poliéster 100 m · Azul marino', 'Hilos', 'Poliéster', 'u', 1200, '#1F2E5A', 26, false, 'Hilo de coser poliéster 100 m · Azul marino. Hilos · Poliéster. Precio por unidad.'),
  ('hilo-de-coser-poliester-100-m-rojo', 'Hilo de coser poliéster 100 m · Rojo', 'Hilos', 'Poliéster', 'u', 1200, '#C62828', 18, false, 'Hilo de coser poliéster 100 m · Rojo. Hilos · Poliéster. Precio por unidad.'),
  ('hilo-de-coser-poliester-100-m-beige', 'Hilo de coser poliéster 100 m · Beige', 'Hilos', 'Poliéster', 'u', 1200, '#D8C3A0', 22, false, 'Hilo de coser poliéster 100 m · Beige. Hilos · Poliéster. Precio por unidad.'),
  ('hilo-de-algodon-mercerizado-200-m-crudo', 'Hilo de algodón mercerizado 200 m · Crudo', 'Hilos', 'Algodón', 'u', 1900, '#EDE3CF', 15, false, 'Hilo de algodón mercerizado 200 m · Crudo. Hilos · Algodón. Precio por unidad.'),
  ('hilo-de-algodon-mercerizado-200-m-verde-salvia', 'Hilo de algodón mercerizado 200 m · Verde salvia', 'Hilos', 'Algodón', 'u', 1900, '#8FA88A', 11, false, 'Hilo de algodón mercerizado 200 m · Verde salvia. Hilos · Algodón. Precio por unidad.'),
  ('cono-de-hilo-overlock-5000-yd-blanco', 'Cono de hilo overlock 5000 yd · Blanco', 'Hilos', 'Overlock', 'u', 4800, '#F5F2EC', 20, true, 'Cono de hilo overlock 5000 yd · Blanco. Hilos · Overlock. Precio por unidad.'),
  ('cono-de-hilo-overlock-5000-yd-negro', 'Cono de hilo overlock 5000 yd · Negro', 'Hilos', 'Overlock', 'u', 4800, '#211E1B', 17, false, 'Cono de hilo overlock 5000 yd · Negro. Hilos · Overlock. Precio por unidad.'),
  ('madeja-de-hilo-para-bordar-set-12-colores', 'Madeja de hilo para bordar · Set 12 colores', 'Hilos', 'Bordar', 'pack', 5200, '#F2803C', 9, true, 'Madeja de hilo para bordar · Set 12 colores. Hilos · Bordar. Precio por pack.'),
  ('hilo-metalizado-para-bordar-dorado', 'Hilo metalizado para bordar · Dorado', 'Hilos', 'Bordar', 'u', 1600, '#C9A14A', 14, false, 'Hilo metalizado para bordar · Dorado. Hilos · Bordar. Precio por unidad.'),
  ('hilo-elastico-para-fruncir-blanco', 'Hilo elástico para fruncir · Blanco', 'Hilos', 'Elástico', 'u', 1400, '#FFFFFF', 12, false, 'Hilo elástico para fruncir · Blanco. Hilos · Elástico. Precio por unidad.'),
  ('boton-4-agujeros-15-mm-nacar', 'Botón 4 agujeros 15 mm · Nácar', 'Botones', '4 agujeros', 'pack', 1800, '#F1EADF', 40, true, 'Botón 4 agujeros 15 mm · Nácar. Botones · 4 agujeros. Precio por pack.'),
  ('boton-4-agujeros-15-mm-negro', 'Botón 4 agujeros 15 mm · Negro', 'Botones', '4 agujeros', 'pack', 1600, '#1F1C1A', 36, false, 'Botón 4 agujeros 15 mm · Negro. Botones · 4 agujeros. Precio por pack.'),
  ('boton-4-agujeros-20-mm-madera', 'Botón 4 agujeros 20 mm · Madera', 'Botones', '4 agujeros', 'pack', 2400, '#9C6B3F', 21, false, 'Botón 4 agujeros 20 mm · Madera. Botones · 4 agujeros. Precio por pack.'),
  ('boton-camisero-11-mm-blanco', 'Botón camisero 11 mm · Blanco', 'Botones', '2 agujeros', 'pack', 1300, '#FBFAF6', 55, false, 'Botón camisero 11 mm · Blanco. Botones · 2 agujeros. Precio por pack.'),
  ('boton-camisero-11-mm-celeste', 'Botón camisero 11 mm · Celeste', 'Botones', '2 agujeros', 'pack', 1300, '#9CC3DE', 19, false, 'Botón camisero 11 mm · Celeste. Botones · 2 agujeros. Precio por pack.'),
  ('boton-con-pie-forrado-18-mm-negro', 'Botón con pie forrado 18 mm · Negro', 'Botones', 'Con pie', 'pack', 2900, '#262220', 8, false, 'Botón con pie forrado 18 mm · Negro. Botones · Con pie. Precio por pack.'),
  ('boton-metalico-con-pie-20-mm-dorado', 'Botón metálico con pie 20 mm · Dorado', 'Botones', 'Con pie', 'pack', 3600, '#C8A04A', 13, false, 'Botón metálico con pie 20 mm · Dorado. Botones · Con pie. Precio por pack.'),
  ('boton-de-jean-a-presion-17-mm-cobre', 'Botón de jean a presión 17 mm · Cobre', 'Botones', 'Jean', 'pack', 3200, '#A0643A', 24, true, 'Botón de jean a presión 17 mm · Cobre. Botones · Jean. Precio por pack.'),
  ('boton-de-jean-a-presion-17-mm-niquel', 'Botón de jean a presión 17 mm · Níquel', 'Botones', 'Jean', 'pack', 3200, '#A7A9AC', 27, false, 'Botón de jean a presión 17 mm · Níquel. Botones · Jean. Precio por pack.'),
  ('boton-infantil-corazon-14-mm-rosa', 'Botón infantil corazón 14 mm · Rosa', 'Botones', 'Infantiles', 'pack', 2100, '#F48FB1', 16, false, 'Botón infantil corazón 14 mm · Rosa. Botones · Infantiles. Precio por pack.'),
  ('boton-infantil-estrella-14-mm-amarillo', 'Botón infantil estrella 14 mm · Amarillo', 'Botones', 'Infantiles', 'pack', 2100, '#F2C94C', 10, false, 'Botón infantil estrella 14 mm · Amarillo. Botones · Infantiles. Precio por pack.'),
  ('broche-a-presion-metalico-10-mm-plateado', 'Broche a presión metálico 10 mm · Plateado', 'Botones', 'Broches', 'pack', 1700, '#BFC3C7', 33, false, 'Broche a presión metálico 10 mm · Plateado. Botones · Broches. Precio por pack.'),
  ('broche-de-gancho-y-presilla-negro', 'Broche de gancho y presilla · Negro', 'Botones', 'Broches', 'pack', 1500, '#1E1B19', 29, false, 'Broche de gancho y presilla · Negro. Botones · Broches. Precio por pack.'),
  ('cierre-invisible-20-cm-negro', 'Cierre invisible 20 cm · Negro', 'Cierres', 'Invisibles', 'u', 900, '#1E1B19', 60, true, 'Cierre invisible 20 cm · Negro. Cierres · Invisibles. Precio por unidad.'),
  ('cierre-invisible-20-cm-rosa', 'Cierre invisible 20 cm · Rosa', 'Cierres', 'Invisibles', 'u', 900, '#EC1968', 22, false, 'Cierre invisible 20 cm · Rosa. Cierres · Invisibles. Precio por unidad.'),
  ('cierre-invisible-60-cm-blanco', 'Cierre invisible 60 cm · Blanco', 'Cierres', 'Invisibles', 'u', 1400, '#F7F4EE', 18, false, 'Cierre invisible 60 cm · Blanco. Cierres · Invisibles. Precio por unidad.'),
  ('cierre-metalico-de-jean-18-cm-bronce', 'Cierre metálico de jean 18 cm · Bronce', 'Cierres', 'Metálicos', 'u', 1300, '#9C6B3F', 35, true, 'Cierre metálico de jean 18 cm · Bronce. Cierres · Metálicos. Precio por unidad.'),
  ('cierre-metalico-desmontable-60-cm-plata', 'Cierre metálico desmontable 60 cm · Plata', 'Cierres', 'Metálicos', 'u', 3400, '#BFC3C7', 12, false, 'Cierre metálico desmontable 60 cm · Plata. Cierres · Metálicos. Precio por unidad.'),
  ('cierre-diente-de-perro-20-cm-azul', 'Cierre diente de perro 20 cm · Azul', 'Cierres', 'Diente de perro', 'u', 1100, '#2F5DA8', 20, false, 'Cierre diente de perro 20 cm · Azul. Cierres · Diente de perro. Precio por unidad.'),
  ('cierre-diente-de-perro-desmontable-70-cm-negro', 'Cierre diente de perro desmontable 70 cm · Negro', 'Cierres', 'Diente de perro', 'u', 3900, '#1E1B19', 9, false, 'Cierre diente de perro desmontable 70 cm · Negro. Cierres · Diente de perro. Precio por unidad.'),
  ('cierre-diente-de-perro-20-cm-verde', 'Cierre diente de perro 20 cm · Verde', 'Cierres', 'Diente de perro', 'u', 1100, '#2F9E6B', 14, false, 'Cierre diente de perro 20 cm · Verde. Cierres · Diente de perro. Precio por unidad.'),
  ('cierre-por-metro-n-5-negro', 'Cierre por metro N°5 · Negro', 'Cierres', 'Por metro', 'mts', 1800, '#1E1B19', 45, true, 'Cierre por metro N°5 · Negro. Cierres · Por metro. Precio por metro.'),
  ('cierre-por-metro-n-5-beige', 'Cierre por metro N°5 · Beige', 'Cierres', 'Por metro', 'mts', 1800, '#D8C3A0', 30, false, 'Cierre por metro N°5 · Beige. Cierres · Por metro. Precio por metro.'),
  ('deslizador-para-cierre-n-5-pack-x10', 'Deslizador para cierre N°5 · Pack x10', 'Cierres', 'Deslizadores', 'pack', 2200, '#BFC3C7', 16, false, 'Deslizador para cierre N°5 · Pack x10. Cierres · Deslizadores. Precio por pack.'),
  ('deslizador-para-cierre-invisible-pack-x10', 'Deslizador para cierre invisible · Pack x10', 'Cierres', 'Deslizadores', 'pack', 2000, '#1E1B19', 11, false, 'Deslizador para cierre invisible · Pack x10. Cierres · Deslizadores. Precio por pack.'),
  ('elastico-plano-10-mm-blanco', 'Elástico plano 10 mm · Blanco', 'Elásticos', 'Planos', 'mts', 350, '#FBFAF6', 120, true, 'Elástico plano 10 mm · Blanco. Elásticos · Planos. Precio por metro.'),
  ('elastico-plano-20-mm-negro', 'Elástico plano 20 mm · Negro', 'Elásticos', 'Planos', 'mts', 520, '#1E1B19', 90, false, 'Elástico plano 20 mm · Negro. Elásticos · Planos. Precio por metro.'),
  ('elastico-plano-40-mm-blanco', 'Elástico plano 40 mm · Blanco', 'Elásticos', 'Planos', 'mts', 900, '#FBFAF6', 60, false, 'Elástico plano 40 mm · Blanco. Elásticos · Planos. Precio por metro.'),
  ('elastico-de-lycra-13-mm-nude', 'Elástico de lycra 13 mm · Nude', 'Elásticos', 'Lycra', 'mts', 480, '#E3C1A8', 75, true, 'Elástico de lycra 13 mm · Nude. Elásticos · Lycra. Precio por metro.'),
  ('elastico-de-lycra-17-mm-negro', 'Elástico de lycra 17 mm · Negro', 'Elásticos', 'Lycra', 'mts', 560, '#1E1B19', 64, false, 'Elástico de lycra 17 mm · Negro. Elásticos · Lycra. Precio por metro.'),
  ('elastico-redondo-2-mm-blanco', 'Elástico redondo 2 mm · Blanco', 'Elásticos', 'Redondos', 'mts', 220, '#FBFAF6', 140, false, 'Elástico redondo 2 mm · Blanco. Elásticos · Redondos. Precio por metro.'),
  ('elastico-redondo-3-mm-negro', 'Elástico redondo 3 mm · Negro', 'Elásticos', 'Redondos', 'mts', 260, '#1E1B19', 110, false, 'Elástico redondo 3 mm · Negro. Elásticos · Redondos. Precio por metro.'),
  ('elastico-con-puntilla-15-mm-rosa', 'Elástico con puntilla 15 mm · Rosa', 'Elásticos', 'Con puntilla', 'mts', 690, '#F48FB1', 38, false, 'Elástico con puntilla 15 mm · Rosa. Elásticos · Con puntilla. Precio por metro.'),
  ('elastico-con-puntilla-15-mm-blanco', 'Elástico con puntilla 15 mm · Blanco', 'Elásticos', 'Con puntilla', 'mts', 690, '#FBFAF6', 41, false, 'Elástico con puntilla 15 mm · Blanco. Elásticos · Con puntilla. Precio por metro.'),
  ('elastico-para-cintura-35-mm-negro', 'Elástico para cintura 35 mm · Negro', 'Elásticos', 'Cintura', 'mts', 850, '#1E1B19', 5, false, 'Elástico para cintura 35 mm · Negro. Elásticos · Cintura. Precio por metro.'),
  ('elastico-para-cintura-35-mm-blanco', 'Elástico para cintura 35 mm · Blanco', 'Elásticos', 'Cintura', 'mts', 850, '#FBFAF6', 0, false, 'Elástico para cintura 35 mm · Blanco. Elásticos · Cintura. Precio por metro.'),
  ('elastico-para-bretel-afelpado-12-mm-nude', 'Elástico para bretel afelpado 12 mm · Nude', 'Elásticos', 'Bretel', 'mts', 640, '#E3C1A8', 27, false, 'Elástico para bretel afelpado 12 mm · Nude. Elásticos · Bretel. Precio por metro.')
on conflict (slug) do update set
  titulo = excluded.titulo, categoria = excluded.categoria, subcategoria = excluded.subcategoria,
  unidad = excluded.unidad, precio = excluded.precio, color = excluded.color,
  stock = excluded.stock, destacado = excluded.destacado, descripcion = excluded.descripcion;
